server:
  port: 5860
spring:
  redis:
    host: 47.112.35.150
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 12000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  application:
    name: item-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.112.35.150:3306/ruiqing?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: ljzLw5860__
    #hikari:
      #maximum-pool-size: 30
      #minimum-idle: 10
    #url: jdbc:postgresql://47.112.35.150:5432/postgres
    #username: root
    #password: 123456
    #driverClassName: org.postgresql.Driver
  mail:
    host: smtp.163.com #SMTP服务器地址
    username:  laivie #登陆账号
    password: Lw12344321. #登陆密码（或授权码）
    properties:
      from: laivie@163.com #邮件发信人（即真实邮箱）
  thymeleaf:
    cache: false
    prefix: classpath:/views/
  servlet:
    multipart:
      max-file-size: 10MB #限制单个文件大小
      max-request-size: 50MB #限制请求总量
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7061/eureka/
      #defaultZone: http://imsdl-eureka:18080/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

ripples:
  resource:
    offsiteLogin: N
    doNotCheckUrls:
      - /api
      - /login
      - /logout
      - /ssologin
      - /upload
      - /druid
      - /i18n
      - /swagger
    commonUrls: