server:
  port: 5860
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  application:
    name: item-service
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    #url: jdbc:mysql://10.201.103.141:3306/imsdlsit?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    #username: imsdl
    #password: Crpower&Ims#2020
    #hikari:
      #maximum-pool-size: 30
      #minimum-idle: 10
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7061/eureka/
      #defaultZone: http://imsdl-eureka:18080/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

ripples:
  resource:
    offsiteLogin: N
    doNotCheckUrls:
      - /api
      - /login
      - /logout
      - /ssologin
      - /upload
      - /druid
      - /i18n
      - /swagger
    commonUrls: